services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build: . 
    restart: always
    working_dir: /var/www/html
    volumes:
      # Data Persistence
      - ./data/wordpress/wp-content:/var/www/html/wp-content
      - ./data/wordpress/uploads:/var/www/html/wp-content/uploads
 
      # Configs
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./.env:/var/www/html/.env
      - ./data/wordpress/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./composer.json:/var/www/html/composer.json
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379
      WORDPRESS_REDIS_PASSWORD: ${REDIS_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '512M');
        define('DISALLOW_FILE_EDIT', true);
        define('WP_HOME', 'https://${HOSTNAME}');
        define('WP_SITEURL', 'https://${HOSTNAME}');
       # Pass OIDC Variables to Container

      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_SCOPE: ${OIDC_SCOPE}
      OIDC_ENDPOINT_LOGIN: ${OIDC_ENDPOINT_LOGIN}
      OIDC_ENDPOINT_USERINFO: ${OIDC_ENDPOINT_USERINFO}
      OIDC_ENDPOINT_TOKEN: ${OIDC_ENDPOINT_TOKEN}
      OIDC_ENDPOINT_LOGOUT: ${OIDC_ENDPOINT_LOGOUT}
      OIDC_IDENTITY_KEY: ${OIDC_IDENTITY_KEY}
      OIDC_NICKNAME_KEY: ${OIDC_NICKNAME_KEY}
      OIDC_EMAIL_FORMAT: ${OIDC_EMAIL_FORMAT}
      OIDC_DISPLAYNAME_FORMAT: ${OIDC_DISPLAYNAME_FORMAT}
      
      # Boolean Flags
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS}
      OIDC_CREATE_IF_NOT_EXISTS: ${OIDC_CREATE_IF_NOT_EXISTS}
      OIDC_REDIRECT_BACK: ${OIDC_REDIRECT_BACK}
      OIDC_IDENTIFY_WITH_USERNAME: ${OIDC_IDENTIFY_WITH_USERNAME}
      OIDC_ENABLE_REFRESH_TOKEN: ${OIDC_ENABLE_REFRESH_TOKEN}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY}

    networks:
      - traefik-net
      - internal-net
    depends_on:
      - db
      - redis

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # service
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_app.loadbalancer.server.port=80"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_app.loadbalancer.server.scheme=http"

      # main router
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.tls.certresolver=le"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.service=${COMPOSE_PROJECT_NAME}_app"

      # www(http) to www(https) routers
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_http.middlewares=${COMPOSE_PROJECT_NAME}_app_redirect_to_https@docker"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_redirect_to_https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_redirect_to_https.redirectscheme.permanent=true"

      # non-www(https) to www(https) routers
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_nonwww_https.rule=Host(`${TRAEFIK_REDIRECT_TO_WWW}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_nonwww_https.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_nonwww_https.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_nonwww_https.tls.certresolver=le"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_nonwww_https.middlewares=${COMPOSE_PROJECT_NAME}_app_nonwww_https@docker"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_nonwww_https.redirectregex.regex=^https://(.+)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_nonwww_https.redirectregex.replacement=https://www.$${1}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_nonwww_https.redirectregex.permanent=true"
      
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mysql:8.0
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal-net
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - internal-net

volumes:
  db_data:
  redis_data:

networks:
  traefik-net:
    external: true
    name: traefik-net
  internal-net:
    driver: bridge

# docker compose exec app composer require wpackagist-plugin/daggerhart-openid-connect-generic