{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "wordpress.fullname" . }}-credentials
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  encryptedData:
    mariadb-root-password: {{ index (.Values.sealedSecret.encryptedData | default dict) "mariadb-root-password" | default "" | quote }}
    mariadb-password: {{ index (.Values.sealedSecret.encryptedData | default dict) "mariadb-password" | default "" | quote }}
    wordpress-password: {{ index (.Values.sealedSecret.encryptedData | default dict) "wordpress-password" | default "" | quote }}
    oauth-client-secret: {{ index (.Values.sealedSecret.encryptedData | default dict) "oauth-client-secret" | default "" | quote }}
  template:
    metadata:
      name: {{ include "wordpress.fullname" . }}-credentials
      labels:
        {{- include "wordpress.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
