{{- if not .Values.sealedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-credentials
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.secret.mariadbRootPassword | default "" | b64enc | quote }}
  mariadb-password: {{ .Values.secret.mariadbPassword | default "" | b64enc | quote }}
  wordpress-password: {{ .Values.secret.wordpressPassword | default "" | b64enc | quote }}
  oauth-client-secret: {{ .Values.secret.oauthClientSecret | default "" | b64enc | quote }}
{{- end }}
