{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
