apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
automountServiceAccountToken: false
{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.dbServiceAccountName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
automountServiceAccountToken: false
{{- end }}
